package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Date;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class OrdersController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private hello.OrdersRepository ordersRepository;
    @Autowired
    private hello.Order_ProductRepository order_productRepository;
    @Autowired
    private hello.ProductRepository p;
    private static final Logger LOG = LoggerFactory.getLogger(OrdersController.class);



    @RequestMapping(path="/createOrder")
    public @ResponseBody String createOrder(@RequestBody int[] products) {
        Orders o = new Orders();
        o.setDate(new Date());

        ordersRepository.save(o);

        for (Integer x: products) {
            hello.Order_Product order_product = new hello.Order_Product();
            order_product.setProductId(x);
            order_product.setOrderId(o.getId());


            //order_product.setProduct(p.findProductByIntegerId(x));
            order_productRepository.save(order_product);

        }

        LOG.info("new order crated");
        return "Created";
    }


}
