package hello.orders;

import hello.User.AddressController;
import hello.User.UserController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestParam;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


import java.util.*;
import java.util.Date;
import java.util.List;

import hello.products.ProductRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class OrdersController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OrdersRepository ordersRepository;
    @Autowired
    private UserController userController;

    @Autowired
    private Order_ProductRepository order_productRepository;
    @Autowired
    private ProductRepository p;

    @Autowired
    private AddressController addressController;

    private static final Logger LOG = LoggerFactory.getLogger(OrdersController.class);


    @RequestMapping(path="/createOrder")
    public @ResponseBody String createOrder(@RequestBody OrderTemplate param) {

        Orders o = new Orders();
        o.setDate(new Date());
        o.setUser(this.userController.getUserById(param.userId));
        o.setAddress(this.addressController.getAddress(param.addressId));

        ordersRepository.save(o);

        for (Integer x: param.productsIds) {

            Order_Product order_product = new Order_Product();

            order_product.setProduct( p.findProductByIntegerId(x));
            order_product.setOrder(o);
            order_productRepository.save(order_product);
            LOG.info("new order crated");
        }


        return "Created";
    }

    @GetMapping (path="/allOrders")
    public @ResponseBody Iterable<ViewOrder> getAllOrders(@RequestParam Integer userId) {
        List<ViewOrder> result = new ArrayList<ViewOrder>();
        for (Order_Product order: order_productRepository.findAll()) {
            Integer x = order.getOrder().getUser().getId();
            if(x.equals(userId)) {
                if(!result.stream().anyMatch(o -> o.id.equals(order.getOrder().getId()))) {
                    ViewOrder vieworder = new ViewOrder();
                    vieworder.products = new ArrayList<>();
                    vieworder.id = order.getOrder().getId();
                    vieworder.date = order.getOrder().getDate().toString();
                    vieworder.address = order.getOrder().getAddress();

                    vieworder.products.add(order.getProduct());
                    result.add(vieworder);
                }
                else {
                    Integer y = result.size() - 1;
                    result.get(y).products.add(order.getProduct());
                }
            }
        }

        return result;
    }
}
